<?php

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function github_projects_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.github_projects':
      return t('
        <h2>Showcase Github projects in Drupal.</h2>
        <h3>Instructions</h3>
        <p>Unpack in the <em>modules</em> folder (currently in the root of your Drupal 8 installation) and enable in <strong>/admin/modules</strong>.</p>
        <p>Then, visit <strong>/admin/config/development/github_projects</strong> and configure your username and access token.</p>
        <h3>Attention</h3>
        <p>Most bugs have been ironed out, holes covered, features added. But this module is a work in progress. Please report bugs and suggestions.</p>
      ');
  }
}
