<?php
/**
 * @file
 * Github module for integrating github repo information into Drupal.
 */

/**
* Implements hook_help().
*
* Displays help and module information.
*
* @param path
*   Which path of the site we're using to display help
* @param arg
*   Array that holds the current path as returned from arg() function
*/
function github_projects_help($path, $arg)
{
    switch ($path) {
     case "admin/help#github_projects":
       return t("<h2>Showcase Github projects in Drupal.</h2>
        <h3>Instructions</h3>
        <p>Unpack in the <em>modules</em> folder (currently in the root of your Drupal 8 installation) and enable in <strong>/admin/modules</strong>.</p>
        <p>Then, visit <strong>/admin/config/development/github_projects</strong> and configure your access token.</p>
        <h3>Attention</h3>
        <p>Most bugs have been ironed out, holes covered, features added. But this module is a work in progress. Please report bugs and suggestions.</p>
      ");
       break;
    }
}

/**
 * Implements hook_menu().
 *
 * Display menu for monfiguration page.
 */
function github_projects_menu()
{
    $items = array();

    $items['admin/config/development/github_projects'] = array(
    'title' => 'Github projects',
    'description' => 'Configuration for Github projects module',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('github_projects_form'),
    'access arguments' => array('access administration pages'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'src/Form/Github_ProjectsForm.inc',
    );

    return $items;
}
